image: node:24@sha256:64af3819f9275802414d7cdc38c27e9d82bd564dec4d4da87d008255d36c63b4

stages:
    - build
    - deploy

build:
    stage: build
    script:
        - npm ci
        - npm run build
    artifacts:
        paths:
            - _site
    only:
        - main

pages:
    stage: deploy
    dependencies:
        - build
    script:
        - rm -rf public
        - mv _site public
    artifacts:
        paths:
            - public
    only:
        - main